"""
LINE Messaging Functions

Send notifications and reports to LINE groups.

Features:
- Send daily substitute teacher reports
- Send test messages
- Format messages with Thai text

Usage:
    from line_messaging import send_daily_report

    send_daily_report("Report text here")
"""

from linebot.v3.messaging import (
    Configuration,
    ApiClient,
    MessagingApi,
    PushMessageRequest,
    TextMessage
)

from src.config import config


def get_line_bot_api() -> MessagingApi:
    """
    Get LINE Bot API instance (v3).

    Returns:
        MessagingApi instance

    Raises:
        ValueError: If LINE_CHANNEL_ACCESS_TOKEN not set
    """
    if not config.LINE_CHANNEL_ACCESS_TOKEN:
        raise ValueError("LINE_CHANNEL_ACCESS_TOKEN not set in environment")

    configuration = Configuration(access_token=config.LINE_CHANNEL_ACCESS_TOKEN)
    api_client = ApiClient(configuration)
    return MessagingApi(api_client)


def send_message_to_group(message: str, group_id: str = None) -> bool:
    """
    Send a text message to a LINE group.

    Args:
        message: Message text to send
        group_id: Target group ID (uses config.LINE_GROUP_ID if not specified)

    Returns:
        True if successful, False otherwise
    """
    # Use configured group ID if not specified
    if not group_id:
        group_id = config.LINE_GROUP_ID

    if not group_id:
        print("ERROR: LINE_GROUP_ID not set")
        return False

    try:
        # Get LINE Bot API
        line_bot_api = get_line_bot_api()

        # Send message using v3 API
        line_bot_api.push_message(
            PushMessageRequest(
                to=group_id,
                messages=[TextMessage(text=message)]
            )
        )

        print(f"Successfully sent message to group: {group_id}")
        return True

    except ValueError as e:
        print(f"Configuration Error: {e}")
        return False
    except Exception as e:
        print(f"ERROR sending message: {e}")
        import traceback
        traceback.print_exc()
        return False


def send_daily_report(report_text: str) -> bool:
    """
    Send daily substitute teacher report to configured LINE group.

    Args:
        report_text: Report text generated by process_daily_leaves.py

    Returns:
        True if successful, False otherwise
    """
    # Add header emoji for visual appeal
    formatted_message = f"📋 รายงานครูแทน\n\n{report_text}"

    return send_message_to_group(formatted_message)


def send_error_notification(error_message: str) -> bool:
    """
    Send error notification to LINE group.

    Args:
        error_message: Error description

    Returns:
        True if successful, False otherwise
    """
    formatted_message = f"⚠️ เกิดข้อผิดพลาดในระบบ\n\n{error_message}"

    return send_message_to_group(formatted_message)


def send_test_message() -> bool:
    """
    Send a test message to verify LINE integration.

    Returns:
        True if successful, False otherwise
    """
    test_message = (
        "🧪 ทดสอบระบบ LINE Bot\n\n"
        "ระบบจัดการครูแทนทำงานปกติ\n"
        f"เวลาประมวลผลรายวัน: {config.DAILY_PROCESS_TIME} น.\n\n"
        "หากได้รับข้อความนี้ แสดงว่าการตั้งค่า LINE Bot สำเร็จ ✓"
    )

    return send_message_to_group(test_message)


def format_substitute_summary(
    date: str,
    total_absences: int,
    total_periods: int,
    substitutes_found: int
) -> str:
    """
    Format a concise substitute summary for LINE.

    Args:
        date: Date string (YYYY-MM-DD)
        total_absences: Number of absent teachers
        total_periods: Total periods to cover
        substitutes_found: Number of substitutes successfully found

    Returns:
        Formatted message string
    """
    success_rate = (substitutes_found / total_periods * 100) if total_periods > 0 else 0

    message = (
        f"📅 {date}\n\n"
        f"👥 ครูที่ลา: {total_absences} คน\n"
        f"📚 คาบที่ต้องจัดครู: {total_periods} คาบ\n"
        f"✅ จัดครูแทนสำเร็จ: {substitutes_found}/{total_periods} "
        f"({success_rate:.0f}%)\n"
    )

    if substitutes_found < total_periods:
        missing = total_periods - substitutes_found
        message += f"\n⚠️ หาครูแทนไม่ได้: {missing} คาบ"

    return message


def format_detailed_assignment(
    day: str,
    period: int,
    class_id: str,
    subject: str,
    absent_teacher: str,
    substitute_teacher: str
) -> str:
    """
    Format a detailed assignment line.

    Args:
        day: Day of week (e.g., "Mon")
        period: Period number
        class_id: Class ID (e.g., "ป.1")
        subject: Subject name
        absent_teacher: Absent teacher name
        substitute_teacher: Substitute teacher name or None

    Returns:
        Formatted assignment string
    """
    if substitute_teacher:
        return (
            f"{day} คาบ {period} | {class_id} - {subject}\n"
            f"  {absent_teacher} → {substitute_teacher}"
        )
    else:
        return (
            f"{day} คาบ {period} | {class_id} - {subject}\n"
            f"  {absent_teacher} → ❌ ไม่มีครูแทน"
        )


def send_formatted_report(
    date: str,
    absent_teachers: list,
    assignments: list
) -> bool:
    """
    Send a nicely formatted substitute report.

    Args:
        date: Date string
        absent_teachers: List of absent teacher info dicts
        assignments: List of assignment dicts

    Returns:
        True if successful, False otherwise
    """
    # Header
    message_lines = [
        "📋 รายงานครูแทนประจำวัน",
        f"📅 วันที่: {date}",
        "=" * 30,
        ""
    ]

    # Summary
    total_absences = len(set(t['teacher_id'] for t in absent_teachers))
    total_periods = len(assignments)
    substitutes_found = sum(1 for a in assignments if a.get('substitute_teacher'))

    message_lines.append(f"👥 ครูที่ลา: {total_absences} คน")
    message_lines.append(f"📚 จำนวนคาบ: {total_periods} คาบ")
    message_lines.append(f"✅ หาครูแทนได้: {substitutes_found}/{total_periods} คาบ")
    message_lines.append("")

    # Detailed assignments grouped by day
    from collections import defaultdict
    by_day = defaultdict(list)

    for assignment in assignments:
        by_day[assignment['day_id']].append(assignment)

    for day in sorted(by_day.keys()):
        message_lines.append(f"📌 {day}")
        message_lines.append("-" * 20)

        day_assignments = sorted(by_day[day], key=lambda x: x['period_id'])
        for assignment in day_assignments:
            period = assignment['period_id']
            class_id = assignment['class_id']
            subject = assignment['subject_id']
            absent = assignment['teacher_id']
            substitute = assignment.get('substitute_teacher', 'ไม่มีครูแทน')

            if substitute and substitute != 'ไม่มีครูแทน':
                status = "✅"
            else:
                status = "❌"
                substitute = "ไม่มีครูแทน"

            message_lines.append(
                f"{status} คาบ {period} | {class_id} - {subject}\n"
                f"   {absent} → {substitute}"
            )

        message_lines.append("")

    # Footer
    message_lines.append("=" * 30)
    message_lines.append("🤖 สร้างโดยระบบอัตโนมัติ")

    # Join and send
    message = "\n".join(message_lines)

    return send_message_to_group(message)


def main():
    """Test LINE messaging"""
    print("="*60)
    print("Testing LINE Messaging")
    print("="*60)

    # Check configuration
    if not config.LINE_CHANNEL_ACCESS_TOKEN:
        print("\nERROR: LINE_CHANNEL_ACCESS_TOKEN not set")
        print("Please configure your .env file first.")
        print("See LINE_BOT_SETUP.md for instructions.")
        return

    if not config.LINE_GROUP_ID:
        print("\nWARNING: LINE_GROUP_ID not set")
        print("You can still test, but you'll need to specify a group ID manually.")

    # Send test message
    print("\nSending test message...")
    success = send_test_message()

    if success:
        print("✓ Test message sent successfully!")
    else:
        print("✗ Failed to send test message")

    print("\n" + "="*60)


if __name__ == "__main__":
    main()
