"""
Configuration Management

Centralizes all configuration values for the leave request system.
Loads sensitive credentials from environment variables.

Usage:
    from config import config
    spreadsheet_id = config.SPREADSHEET_ID
"""

import os
from pathlib import Path
from dotenv import load_dotenv

# Get project root directory (parent of src/)
PROJECT_ROOT = Path(__file__).parent.parent.absolute()

# Load environment variables from .env file
load_dotenv(PROJECT_ROOT / '.env')


class Config:
    """Central configuration class"""

    # ==================== Google Sheets ====================
    SPREADSHEET_ID = os.getenv(
        'SPREADSHEET_ID',
        '1KpQZlrJk03ZS_Q0bTWvxHjG9UFiD1xPZGyIsQfRkRWo'  # Default
    )
    LEAVE_LOGS_WORKSHEET = "Leave_Logs"
    LEAVE_REQUESTS_WORKSHEET = "Leave_Requests"
    PENDING_ASSIGNMENTS_WORKSHEET = "Pending_Assignments"

    # Admin verification settings
    REPORT_PREFIX = "[REPORT]"  # Prefix for admin substitution reports
    PENDING_EXPIRATION_DAYS = 7  # Auto-expire pending assignments after N days

    # ==================== File Paths ====================
    CREDENTIALS_FILE = str(PROJECT_ROOT / "credentials.json")
    TIMETABLE_FILE = str(PROJECT_ROOT / "data" / "real_timetable.json")

    # Data files (generated by build_teacher_data.py)
    TEACHER_SUBJECTS_FILE = str(PROJECT_ROOT / "data" / "teacher_subjects.json")
    TEACHER_LEVELS_FILE = str(PROJECT_ROOT / "data" / "teacher_levels.json")
    CLASS_LEVELS_FILE = str(PROJECT_ROOT / "data" / "class_levels.json")
    TEACHER_NAME_MAP_FILE = str(PROJECT_ROOT / "data" / "teacher_name_map.json")
    TEACHER_FULL_NAMES_FILE = str(PROJECT_ROOT / "data" / "teacher_full_names.json")

    # ==================== LINE Bot ====================
    LINE_CHANNEL_SECRET = os.getenv('LINE_CHANNEL_SECRET', '')
    LINE_CHANNEL_ACCESS_TOKEN = os.getenv('LINE_CHANNEL_ACCESS_TOKEN', '')

    # Group IDs for two-group notification system
    LINE_TEACHER_GROUP_ID = os.getenv('LINE_TEACHER_GROUP_ID', '')  # Teachers submit leave requests
    LINE_ADMIN_GROUP_ID = os.getenv('LINE_ADMIN_GROUP_ID', '')  # Admins receive all notifications
    LINE_GROUP_ID = os.getenv('LINE_GROUP_ID', '')  # Legacy: fallback group

    # ==================== OpenRouter AI ====================
    OPENROUTER_API_KEY = os.getenv('OPENROUTER_API_KEY', '')
    OPENROUTER_MODEL = os.getenv('OPENROUTER_MODEL', 'deepseek/deepseek-r1')  # DeepSeek R1 (paid model, configurable via .env)
    OPENROUTER_API_URL = "https://openrouter.ai/api/v1/chat/completions"

    # ==================== System Settings ====================
    TIMEZONE = "Asia/Bangkok"
    WORKING_DAYS = ["Mon", "Tue", "Wed", "Thu", "Fri"]
    DAILY_PROCESS_TIME = "08:55"  # Time to run daily processing (24h format)

    # Flask webhook settings
    WEBHOOK_HOST = os.getenv('WEBHOOK_HOST', '0.0.0.0')
    WEBHOOK_PORT = int(os.getenv('WEBHOOK_PORT', '5000'))
    DEBUG_MODE = os.getenv('DEBUG_MODE', 'False').lower() == 'true'

    # ==================== Validation ====================
    @classmethod
    def validate(cls):
        """Validate required configuration values"""
        errors = []

        # Check LINE Bot credentials for production
        if not cls.LINE_CHANNEL_SECRET and not cls.DEBUG_MODE:
            errors.append("LINE_CHANNEL_SECRET not set in environment")
        if not cls.LINE_CHANNEL_ACCESS_TOKEN and not cls.DEBUG_MODE:
            errors.append("LINE_CHANNEL_ACCESS_TOKEN not set in environment")

        # Check OpenRouter API key for AI parsing
        if not cls.OPENROUTER_API_KEY and not cls.DEBUG_MODE:
            errors.append("OPENROUTER_API_KEY not set in environment")

        # Check Google credentials file exists
        if not os.path.exists(cls.CREDENTIALS_FILE):
            errors.append(f"Google credentials file not found: {cls.CREDENTIALS_FILE}")

        # Check timetable file exists
        if not os.path.exists(cls.TIMETABLE_FILE):
            errors.append(f"Timetable file not found: {cls.TIMETABLE_FILE}")

        return errors

    @classmethod
    def print_status(cls):
        """Print configuration status (for debugging)"""
        print("="*60)
        print("Configuration Status")
        print("="*60)
        print(f"Spreadsheet ID: {cls.SPREADSHEET_ID}")
        print(f"Credentials File: {cls.CREDENTIALS_FILE} " +
              ("(exists)" if os.path.exists(cls.CREDENTIALS_FILE) else "(MISSING)"))
        print(f"Timetable File: {cls.TIMETABLE_FILE} " +
              ("(exists)" if os.path.exists(cls.TIMETABLE_FILE) else "(MISSING)"))
        print(f"LINE Channel Secret: {'Set' if cls.LINE_CHANNEL_SECRET else 'NOT SET'}")
        print(f"LINE Access Token: {'Set' if cls.LINE_CHANNEL_ACCESS_TOKEN else 'NOT SET'}")
        print(f"LINE Teacher Group ID: {'Set' if cls.LINE_TEACHER_GROUP_ID else 'NOT SET'}")
        print(f"LINE Admin Group ID: {'Set' if cls.LINE_ADMIN_GROUP_ID else 'NOT SET'}")
        print(f"LINE Legacy Group ID: {'Set' if cls.LINE_GROUP_ID else 'NOT SET'}")
        print(f"OpenRouter API Key: {'Set' if cls.OPENROUTER_API_KEY else 'NOT SET'}")
        print(f"Debug Mode: {cls.DEBUG_MODE}")
        print("="*60)

        # Validation check
        errors = cls.validate()
        if errors:
            print("\nConfiguration Errors:")
            for error in errors:
                print(f"  - {error}")
        else:
            print("\nConfiguration: OK")


# Create singleton instance
config = Config()


if __name__ == "__main__":
    # Test configuration
    config.print_status()
